using Microsoft.EntityFrameworkCore;

namespace Edelstein.Data.Msts.Persistence;

public class MstDbContext : DbContext
{
    public MstDbContext(DbContextOptions<MstDbContext> options) : base(options) { }

    public DbSet<AchievementMst> AchievementMsts { get; set; }
    public DbSet<AdjustTrackingListMst> AdjustTrackingListMsts { get; set; }
    public DbSet<AlbumCardMMst> AlbumCardMMsts { get; set; }
    public DbSet<AlbumMemberTagMMst> AlbumMemberTagMMsts { get; set; }
    public DbSet<AlbumMultiUnitMMst> AlbumMultiUnitMMsts { get; set; }
    public DbSet<AlbumSeriesMMst> AlbumSeriesMMsts { get; set; }
    public DbSet<AlbumSeriesThumbnailAssetMMst> AlbumSeriesThumbnailAssetMMsts { get; set; }
    public DbSet<AlbumUnitMMst> AlbumUnitMMsts { get; set; }
    public DbSet<AlbumUnitPairMMst> AlbumUnitPairMMsts { get; set; }
    public DbSet<AlbumUnitSeriesMMst> AlbumUnitSeriesMMsts { get; set; }
    public DbSet<AlbumUnitTypeMemberTagMMst> AlbumUnitTypeMemberTagMMsts { get; set; }
    public DbSet<AlbumUnitTypeMst> AlbumUnitTypeMsts { get; set; }
    public DbSet<BeginnerMissionMst> BeginnerMissionMsts { get; set; }
    public DbSet<BeginnerMissionRewardMst> BeginnerMissionRewardMsts { get; set; }
    public DbSet<BeginnerMissionRewardSettingMst> BeginnerMissionRewardSettingMsts { get; set; }
    public DbSet<BgmMst> BgmMsts { get; set; }
    public DbSet<BillingProductMst> BillingProductMsts { get; set; }
    public DbSet<BillingProductRewardMst> BillingProductRewardMsts { get; set; }
    public DbSet<BillingShopMst> BillingShopMsts { get; set; }
    public DbSet<BillingSubscriptionMst> BillingSubscriptionMsts { get; set; }
    public DbSet<BillingSubscriptionRewardMst> BillingSubscriptionRewardMsts { get; set; }
    public DbSet<CardCollectionRewardMst> CardCollectionRewardMsts { get; set; }
    public DbSet<CardEvolveConditionMst> CardEvolveConditionMsts { get; set; }
    public DbSet<CardEvolveMst> CardEvolveMsts { get; set; }
    public DbSet<CardGetMst> CardGetMsts { get; set; }
    public DbSet<CardLevelMst> CardLevelMsts { get; set; }
    public DbSet<CardMst> CardMsts { get; set; }
    public DbSet<CardRarityMst> CardRarityMsts { get; set; }
    public DbSet<CardSkillLevelMst> CardSkillLevelMsts { get; set; }
    public DbSet<CardSysVoiceMst> CardSysVoiceMsts { get; set; }
    public DbSet<CharacterGroupMst> CharacterGroupMsts { get; set; }
    public DbSet<CharacterMst> CharacterMsts { get; set; }
    public DbSet<CharacterSysVoiceMst> CharacterSysVoiceMsts { get; set; }
    public DbSet<ChatAttachmentMst> ChatAttachmentMsts { get; set; }
    public DbSet<ChatChapterMst> ChatChapterMsts { get; set; }
    public DbSet<ChatCharacterMst> ChatCharacterMsts { get; set; }
    public DbSet<ChatMst> ChatMsts { get; set; }
    public DbSet<ChatRewardMst> ChatRewardMsts { get; set; }
    public DbSet<ChatRoomMst> ChatRoomMsts { get; set; }
    public DbSet<ChatStampMst> ChatStampMsts { get; set; }
    public DbSet<ChatVoiceKeyMst> ChatVoiceKeyMsts { get; set; }
    public DbSet<ChipsterResultCodeMst> ChipsterResultCodeMsts { get; set; }
    public DbSet<ComicMst> ComicMsts { get; set; }
    public DbSet<CommonBgMovieMst> CommonBgMovieMsts { get; set; }
    public DbSet<ConstMst> ConstMsts { get; set; }
    public DbSet<DateConditionMst> DateConditionMsts { get; set; }
    public DbSet<DateConditionOthersMst> DateConditionOthersMsts { get; set; }
    public DbSet<DialogButtonMst> DialogButtonMsts { get; set; }
    public DbSet<DialogMst> DialogMsts { get; set; }
    public DbSet<EventCardBonusMst> EventCardBonusMsts { get; set; }
    public DbSet<EventLiveMst> EventLiveMsts { get; set; }
    public DbSet<EventMemberRankingMst> EventMemberRankingMsts { get; set; }
    public DbSet<EventMemberRankingRewardMst> EventMemberRankingRewardMsts { get; set; }
    public DbSet<EventMst> EventMsts { get; set; }
    public DbSet<EventPointMst> EventPointMsts { get; set; }
    public DbSet<EventPointRankingMst> EventPointRankingMsts { get; set; }
    public DbSet<EventPointRankingRewardMst> EventPointRankingRewardMsts { get; set; }
    public DbSet<EventPointRewardMst> EventPointRewardMsts { get; set; }
    public DbSet<EventPointSettingsMst> EventPointSettingsMsts { get; set; }
    public DbSet<EventScoreMst> EventScoreMsts { get; set; }
    public DbSet<EventScoreRankingMst> EventScoreRankingMsts { get; set; }
    public DbSet<EventScoreRankingRewardMst> EventScoreRankingRewardMsts { get; set; }
    public DbSet<EventStoryMst> EventStoryMsts { get; set; }
    public DbSet<EventTipsMst> EventTipsMsts { get; set; }
    public DbSet<EventTipsPageMst> EventTipsPageMsts { get; set; }
    public DbSet<EventTopBannerMst> EventTopBannerMsts { get; set; }
    public DbSet<EventTypeMst> EventTypeMsts { get; set; }
    public DbSet<EvolveItemAmountMst> EvolveItemAmountMsts { get; set; }
    public DbSet<EvolveItemConditionMst> EvolveItemConditionMsts { get; set; }
    public DbSet<ExchangeItemMst> ExchangeItemMsts { get; set; }
    public DbSet<ExchangeItemRewardMst> ExchangeItemRewardMsts { get; set; }
    public DbSet<ExchangeMst> ExchangeMsts { get; set; }
    public DbSet<FunctionLockMst> FunctionLockMsts { get; set; }
    public DbSet<GamelibResultCodeMst> GamelibResultCodeMsts { get; set; }
    public DbSet<GroupMst> GroupMsts { get; set; }
    public DbSet<HomeBannerMst> HomeBannerMsts { get; set; }
    public DbSet<HomeBgMst> HomeBgMsts { get; set; }
    public DbSet<ItemMst> ItemMsts { get; set; }
    public DbSet<LimitedLiveMst> LimitedLiveMsts { get; set; }
    public DbSet<LiveBoostMst> LiveBoostMsts { get; set; }
    public DbSet<LiveClearRewardMst> LiveClearRewardMsts { get; set; }
    public DbSet<LiveComboMst> LiveComboMsts { get; set; }
    public DbSet<LiveConditionMst> LiveConditionMsts { get; set; }
    public DbSet<LiveEffectValueMst> LiveEffectValueMsts { get; set; }
    public DbSet<LiveInputResultMst> LiveInputResultMsts { get; set; }
    public DbSet<LiveLaneSkinMst> LiveLaneSkinMsts { get; set; }
    public DbSet<LiveMissionComboMst> LiveMissionComboMsts { get; set; }
    public DbSet<LiveMissionMst> LiveMissionMsts { get; set; }
    public DbSet<LiveMissionRewardMst> LiveMissionRewardMsts { get; set; }
    public DbSet<LiveMst> LiveMsts { get; set; }
    public DbSet<LiveRankingRewardMst> LiveRankingRewardMsts { get; set; }
    public DbSet<LiveRecommendListMst> LiveRecommendListMsts { get; set; }
    public DbSet<LiveRecommendMst> LiveRecommendMsts { get; set; }
    public DbSet<LiveRewardMst> LiveRewardMsts { get; set; }
    public DbSet<LiveRewardSettingMst> LiveRewardSettingMsts { get; set; }
    public DbSet<LiveRuleMst> LiveRuleMsts { get; set; }
    public DbSet<LiveTapEffectMst> LiveTapEffectMsts { get; set; }
    public DbSet<LiveTapSeMst> LiveTapSeMsts { get; set; }
    public DbSet<LocationMst> LocationMsts { get; set; }
    public DbSet<LocationRewardMst> LocationRewardMsts { get; set; }
    public DbSet<LoginBonusMst> LoginBonusMsts { get; set; }
    public DbSet<LoginBonusRewardMst> LoginBonusRewardMsts { get; set; }
    public DbSet<LoginBonusRewardSettingMst> LoginBonusRewardSettingMsts { get; set; }
    public DbSet<LotteryCautionMst> LotteryCautionMsts { get; set; }
    public DbSet<LotteryEffMovieMst> LotteryEffMovieMsts { get; set; }
    public DbSet<LotteryEffMovieRatioMst> LotteryEffMovieRatioMsts { get; set; }
    public DbSet<LotteryImageMst> LotteryImageMsts { get; set; }
    public DbSet<LotteryInfoMst> LotteryInfoMsts { get; set; }
    public DbSet<LotteryItemMst> LotteryItemMsts { get; set; }
    public DbSet<LotteryMst> LotteryMsts { get; set; }
    public DbSet<LotteryPriceMst> LotteryPriceMsts { get; set; }
    public DbSet<LotteryRarityMst> LotteryRarityMsts { get; set; }
    public DbSet<LotteryRewardMst> LotteryRewardMsts { get; set; }
    public DbSet<LotteryStepupMst> LotteryStepupMsts { get; set; }
    public DbSet<MembershipWallpaperMst> MembershipWallpaperMsts { get; set; }
    public DbSet<MissionBannerMst> MissionBannerMsts { get; set; }
    public DbSet<MissionMst> MissionMsts { get; set; }
    public DbSet<MissionRewardMst> MissionRewardMsts { get; set; }
    public DbSet<MovieKeyMst> MovieKeyMsts { get; set; }
    public DbSet<MovieMst> MovieMsts { get; set; }
    public DbSet<MultiDailyDropEffectMst> MultiDailyDropEffectMsts { get; set; }
    public DbSet<MultieventCardBonusMst> MultieventCardBonusMsts { get; set; }
    public DbSet<MultieventMatchingrangeMst> MultieventMatchingrangeMsts { get; set; }
    public DbSet<MultieventPenaltyMst> MultieventPenaltyMsts { get; set; }
    public DbSet<MultieventRankbonusMst> MultieventRankbonusMsts { get; set; }
    public DbSet<MultieventSettingMst> MultieventSettingMsts { get; set; }
    public DbSet<MultiPenaltyMst> MultiPenaltyMsts { get; set; }
    public DbSet<MultiRoomConditionMst> MultiRoomConditionMsts { get; set; }
    public DbSet<MultiRoomSelectMst> MultiRoomSelectMsts { get; set; }
    public DbSet<MusicLevelMst> MusicLevelMsts { get; set; }
    public DbSet<MusicMst> MusicMsts { get; set; }
    public DbSet<MusicShopPriceMst> MusicShopPriceMsts { get; set; }
    public DbSet<NavigationConditionMst> NavigationConditionMsts { get; set; }
    public DbSet<NavigationDialogPageMst> NavigationDialogPageMsts { get; set; }
    public DbSet<NavigationMst> NavigationMsts { get; set; }
    public DbSet<NewSkillMst> NewSkillMsts { get; set; }
    public DbSet<NoticeBirthdayMst> NoticeBirthdayMsts { get; set; }
    public DbSet<NoticeCardImageMst> NoticeCardImageMsts { get; set; }
    public DbSet<NoticeCardMst> NoticeCardMsts { get; set; }
    public DbSet<NoticeGachaMst> NoticeGachaMsts { get; set; }
    public DbSet<NoticeGeneralMst> NoticeGeneralMsts { get; set; }
    public DbSet<NoticeGeneralNavigationMst> NoticeGeneralNavigationMsts { get; set; }
    public DbSet<NoticeGeneralSequenceMst> NoticeGeneralSequenceMsts { get; set; }
    public DbSet<NoticeMusicImageMst> NoticeMusicImageMsts { get; set; }
    public DbSet<NoticeMusicMst> NoticeMusicMsts { get; set; }
    public DbSet<PartVoiceKeyMst> PartVoiceKeyMsts { get; set; }
    public DbSet<PresetBackgroundMst> PresetBackgroundMsts { get; set; }
    public DbSet<PresetForegroundMst> PresetForegroundMsts { get; set; }
    public DbSet<ReleaseLabelMst> ReleaseLabelMsts { get; set; }
    public DbSet<ResourceDownloadMst> ResourceDownloadMsts { get; set; }
    public DbSet<ResultCodeMst> ResultCodeMsts { get; set; }
    public DbSet<RhythmIconMst> RhythmIconMsts { get; set; }
    public DbSet<SceneTitleMst> SceneTitleMsts { get; set; }
    public DbSet<SeMst> SeMsts { get; set; }
    public DbSet<ShopItemMst> ShopItemMsts { get; set; }
    public DbSet<ShopRewardMst> ShopRewardMsts { get; set; }
    public DbSet<SkillCenterEffectMst> SkillCenterEffectMsts { get; set; }
    public DbSet<SkillCenterMst> SkillCenterMsts { get; set; }
    public DbSet<SoundKeyMst> SoundKeyMsts { get; set; }
    public DbSet<StampMst> StampMsts { get; set; }
    public DbSet<StarEventCardBonusMst> StarEventCardBonusMsts { get; set; }
    public DbSet<StarEventLevelMst> StarEventLevelMsts { get; set; }
    public DbSet<StarEventLevelRewardMst> StarEventLevelRewardMsts { get; set; }
    public DbSet<StarEventLevelRewardSettingMst> StarEventLevelRewardSettingMsts { get; set; }
    public DbSet<StarEventSettingMst> StarEventSettingMsts { get; set; }
    public DbSet<StoryMst> StoryMsts { get; set; }
    public DbSet<StoryPartMst> StoryPartMsts { get; set; }
    public DbSet<StoryReleaseMst> StoryReleaseMsts { get; set; }
    public DbSet<StoryRewardMst> StoryRewardMsts { get; set; }
    public DbSet<SubscriptionImageMst> SubscriptionImageMsts { get; set; }
    public DbSet<SysVoiceKeyMst> SysVoiceKeyMsts { get; set; }
    public DbSet<TextMst> TextMsts { get; set; }
    public DbSet<TitleMst> TitleMsts { get; set; }
    public DbSet<TitleScreenMst> TitleScreenMsts { get; set; }
    public DbSet<UrlMst> UrlMsts { get; set; }
    public DbSet<UserRankMst> UserRankMsts { get; set; }
    public DbSet<UserRankRewardMst> UserRankRewardMsts { get; set; }
    public DbSet<VoiceKeyMst> VoiceKeyMsts { get; set; }
    public DbSet<VoiceMst> VoiceMsts { get; set; }
    public DbSet<WipeMst> WipeMsts { get; set; }
    public DbSet<WipePlayListMst> WipePlayListMsts { get; set; }
}
